commonLabels:
  app: eda-ui
resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ansible-events-ui
  newName: eda
  newTag: latest
